### Bài 1. Tạo Tensor cơ bản
Tạo một Tensor số nguyên kích thước 2 × 3 và hiển thị kết quả.

In [4]:
import torch


a = torch.tensor(
    [[1,2,3],
     [4,5,6]],
     dtype=torch.int32

)

print (a)

   

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


Bài 2. Tạo các Tensor thường dùng
Thực hành tạo Tensor ngẫu nhiên, Tensor toàn số 0, toàn số 1 và ma trận đơn vị.

In [6]:
import torch
a = torch.rand(3,4)
b= torch.randn(3,4)
c= torch.zeros(2,3)
d = torch.ones(2,3)
e =torch.eye(4)

print(a)
print(b)
print(c)
print(d)
print(e)

tensor([[0.6241, 0.3652, 0.3424, 0.6738],
        [0.2711, 0.3770, 0.0085, 0.7160],
        [0.8351, 0.5180, 0.3410, 0.4474]])
tensor([[-0.4610, -0.6111, -0.2709,  1.0195],
        [ 1.5879, -0.6081,  0.0684, -1.9211],
        [ 0.7358,  0.7002, -1.6370,  0.6741]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


In [7]:
import torch
a = torch.full((5,5),10)
print(a)

tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])


Bài 3. Kiểm tra thông tin Tensor
Sử dụng shape, size(), ndim và dtype để kiểm tra các thuộc tính của Tensor.

In [12]:
import torch
a =torch.zeros(2,3,4) 
print(a)
print("Shape", a.shape)
print("Size", a.size())
print("Number of dimensions", a.ndim)
print("Data type", a.dtype)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Shape torch.Size([2, 3, 4])
Size torch.Size([2, 3, 4])
Number of dimensions 3
Data type torch.float32


Bài 4. Slicing và Indexing
Truy xuất một phần dữ liệu từ Tensor nhiều chiều.

In [2]:
import torch

a = torch.randn(3,4,5)
print ("Original tensor:")
print(a)

print("\n Tensor a[1]")
print (a[1])

print ("\n Tensor a[1:, 2:4]:")
print (a[1:, 2:4])


print(a[:, :, -2:])

Original tensor:
tensor([[[-0.7780,  0.4709,  0.5813, -0.2564,  0.7212],
         [-0.9453,  1.1417, -1.2492, -0.1235,  0.1553],
         [-1.5241,  0.9142, -0.6849, -0.7655,  1.1523],
         [-1.1992,  0.1814,  1.3634, -0.1298,  0.4118]],

        [[ 2.3764, -0.9291, -2.3193, -0.2394,  0.1228],
         [ 0.1810, -0.2632,  0.3455, -1.3855,  2.0054],
         [-0.3556, -0.9759, -0.9284,  0.7296,  1.0024],
         [-0.2150, -1.0268, -1.2043, -1.8460, -0.7714]],

        [[ 0.2167, -0.3706, -0.5987, -0.0199, -0.3457],
         [ 0.2064,  0.0059,  1.1201,  0.5775, -0.2221],
         [ 1.5820,  1.0488, -0.3982, -0.7524,  0.0556],
         [-0.6479,  0.2662,  1.0098, -0.7684,  0.8367]]])

 Tensor a[1]
tensor([[ 2.3764, -0.9291, -2.3193, -0.2394,  0.1228],
        [ 0.1810, -0.2632,  0.3455, -1.3855,  2.0054],
        [-0.3556, -0.9759, -0.9284,  0.7296,  1.0024],
        [-0.2150, -1.0268, -1.2043, -1.8460, -0.7714]])

 Tensor a[1:, 2:4]:
tensor([[[-0.3556, -0.9759, -0.9284,  0.7296,  1.

Bài 5. Reshape và Flatten
Thay đổi hình dạng Tensor mà không làm thay đổi số phần tử.

In [1]:


import torch
a = torch.randn(3, 4)
print("Original:")
print(a)
print("\nFlatten:")
print(a.ravel())
print("\nReshape to 3 x 2 x 2:")
print(a.reshape(3, 2, 2))

Original:
tensor([[-0.5654,  1.3030, -0.1920, -0.1610],
        [ 1.6819, -0.4366, -0.3322,  2.1386],
        [ 0.5729,  0.3584,  1.7582,  0.6450]])

Flatten:
tensor([-0.5654,  1.3030, -0.1920, -0.1610,  1.6819, -0.4366, -0.3322,  2.1386,
         0.5729,  0.3584,  1.7582,  0.6450])

Reshape to 3 x 2 x 2:
tensor([[[-0.5654,  1.3030],
         [-0.1920, -0.1610]],

        [[ 1.6819, -0.4366],
         [-0.3322,  2.1386]],

        [[ 0.5729,  0.3584],
         [ 1.7582,  0.6450]]])


Bài 6. Phép toán và nhân ma trận
Thực hiện các phép toán phần tử và phép nhân ma trận bằng toán tử @.

In [5]:
from unittest import result

import torch

a= torch.randn(2,3)
b=torch.randn(2,3)

print("a:")
print(a)
print("b:")
print(b)

print("\n a + b:")
print(a + b)

print("\n a / b")
print(a / b)

print("\na*2")
print(a**2)

print("\n Matrix multiplication:")
print(a @ b.T)


result = a @ b.T
print(result.shape)


a:
tensor([[-1.7681, -1.1196,  0.2713],
        [-0.9214,  1.1617, -1.2622]])
b:
tensor([[ 1.2383,  1.4106, -0.3457],
        [-1.1048,  0.4310,  0.8969]])

 a + b:
tensor([[-0.5298,  0.2911, -0.0744],
        [-2.0262,  1.5928, -0.3652]])

 a / b
tensor([[-1.4279, -0.7937, -0.7848],
        [ 0.8340,  2.6954, -1.4072]])

a*2
tensor([[3.1260, 1.2534, 0.0736],
        [0.8490, 1.3496, 1.5931]])

 Matrix multiplication:
tensor([[-3.8624,  1.7141],
        [ 0.9341,  0.3865]])
torch.Size([2, 2])


Bài 7. Các hàm thống kê trên Tensor
Tính trung bình, độ lệch chuẩn và tổng tích lũy theo từng cột.

In [ ]:
import torch

a = torch.randn(3,4)

print(a)
print("\n Mean")
print(torch.mean(a, dim=0))

print ("\n Standard deviation:")
print(torch.std(a,dim=0))

print("\nCumulative sum:")
print(torch.cumsum(a, dim =0))




### THAY DIM =1 

a = torch.randn(3,4)

print(a)
print("\n Mean")
print(torch.mean(a, dim=1))

print ("\n Standard deviation:")
print(torch.std(a,dim=1))

print("\nCumulative sum:")
print(torch.cumsum(a, dim =1))

tensor([[-0.3970, -0.6089,  0.0865,  1.9316],
        [ 1.4158, -0.2321,  0.5019,  0.2536],
        [-0.1836, -1.4593,  0.0142, -0.7412]])

 Mean
tensor([ 0.2784, -0.7668,  0.2009,  0.4813])

 Standard deviation:
tensor([0.9908, 0.6287, 0.2632, 1.3509])

Cumulative sum:
tensor([[-0.3970, -0.6089,  0.0865,  1.9316],
        [ 1.0187, -0.8410,  0.5884,  2.1852],
        [ 0.8351, -2.3004,  0.6026,  1.4440]])
tensor([[ 0.9211,  0.4108,  0.5096, -1.3703],
        [ 1.2040, -0.1695, -0.4809, -0.9490],
        [ 0.1355, -0.1099, -0.7961,  0.4949]])

 Mean
tensor([ 0.1178, -0.0989, -0.0689])

 Standard deviation:
tensor([1.0164, 0.9258, 0.5447])

Cumulative sum:
tensor([[ 0.9211,  1.3319,  1.8415,  0.4712],
        [ 1.2040,  1.0344,  0.5536, -0.3955],
        [ 0.1355,  0.0256, -0.7705, -0.2756]])


: 

Bài 8. Autograd cơ bản
Tạo biến có requires_grad=True và dùng backward() để tính đạo hàm tự động.

In [2]:
import torch

x = torch.tensor(
    3.6,
    requires_grad=True
)

y = x*x

y.backward()

print("x=", x)
print("y=", y)
print("x.grad =", x.grad)

### Đổi hàm thành y = 3*x**2 + 2*x + 1 và kiểm tra gradient.

y = 3*x**2 + 2*x + 1

y.backward()

print("x=", x)
print("y=", y)
print("x.grad =", x.grad)



x= tensor(3.6000, requires_grad=True)
y= tensor(12.9600, grad_fn=<MulBackward0>)
x.grad = tensor(7.2000)
x= tensor(3.6000, requires_grad=True)
y= tensor(47.0800, grad_fn=<AddBackward0>)
x.grad = tensor(30.8000)


Bài 9. Gradient Descent tìm hệ số đa thức
Sinh dữ liệu từ đa thức y = x2 + 2x + 3, sau đó dùng NAdam và autograd để tìm lại ba hệ số.

In [5]:
import numpy as np
import torch

polynomial = np.poly1d([1,2,3])
N=20

X= np.random.randn(N, 1) * 5
Y = polynomial(X)

XX = np.hstack([
    X * X,
    X,
    np.ones_like(X)
])

w= torch.randn(3,1, requires_grad=True)
x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)


optimizer = torch.optim.SGD([w], lr=0.01)
print ("Inital coefficients:")
print (w)

for epoch in range(1000):
    optimizer.zero_grad()
    y_pred = x @ w
    mse = torch.mean(torch.square(y - y_pred))
    mse.backward()
    optimizer.step()

print("Learned coefficients:")
print(w)

# so sánh
print("Hệ số học được:", w.detach().flatten())
print("Hệ số đúng:    ", torch.tensor([1., 2., 3.]))


Inital coefficients:
tensor([[-0.3431],
        [-1.8934],
        [-1.3782]], requires_grad=True)
Learned coefficients:
tensor([[nan],
        [nan],
        [nan]], requires_grad=True)
Hệ số học được: tensor([nan, nan, nan])
Hệ số đúng:     tensor([1., 2., 3.])


Bài 10. Giải hệ phương trình bằng Autograd
Tối thiểu hóa tổng sai số bình phương để tìm A, B, C, D thỏa bốn phương trình.

In [17]:
import random
import torch
A = torch.tensor(random.random(), requires_grad=True)
B = torch.tensor(random.random(), requires_grad=True)
C = torch.tensor(random.random(), requires_grad=True)
D = torch.tensor(random.random(), requires_grad=True)
EPOCHS = 2000
optimizer = torch.optim.NAdam([A, B, C, D], lr=0.01)
for _ in range(EPOCHS):
    y1 = A + B - 9
    y2 = C - D - 1
    y3 = A + C - 8
    y4 = B - D - 2
    sqerr = y1*y1 + y2*y2 + y3*y3 + y4*y4
    optimizer.zero_grad()
    sqerr.backward()
    optimizer.step()
print("A =", A)
print("B =", B)
print("C =", C)
print("D =", D)

A = tensor(4.3833, requires_grad=True)
B = tensor(4.6167, requires_grad=True)
C = tensor(3.6167, requires_grad=True)
D = tensor(2.6167, requires_grad=True)


Bài 11. Viết chương trình PyTorch để thực hiện các yêu cầu sau:
• Tạo Tensor X có 24 phần tử và reshape lần lượt thành 4 × 6, 2 × 12 và 2 × 3 × 4.
• Tạo hai Tensor A, B kích thước 3 × 4; tính A+B, A*B, A/B, trung bình theo cột và độ lệch chuẩn theo cột.
• Cho y = 2x2 + 5x + 3. Dùng autograd tính dy/dx tại x = 2 và kiểm tra bằng phép tính thủ công.
• Thay đa thức trong Bài 9 bằng y = 2x2 - 3x + 5; huấn luyện và cho biết các hệ số tìm được.

In [1]:
import torch

# 1. Tensor X co 24 phan tu va reshape theo 3 cach
X = torch.arange(1, 25)
X_4x6 = X.reshape(4, 6)
X_2x12 = X.reshape(2, 12)
X_2x3x4 = X.reshape(2, 3, 4)

print("X =\n", X)
print("X reshape (4, 6) =\n", X_4x6)
print("X reshape (2, 12) =\n", X_2x12)
print("X reshape (2, 3, 4) =\n", X_2x3x4)

# 2. Phep tinh tren hai Tensor A, B kich thuoc 3 x 4
A = torch.tensor([[1., 2., 3., 4.],
                  [5., 6., 7., 8.],
                  [9., 10., 11., 12.]])
B = torch.tensor([[2., 4., 6., 8.],
                  [1., 2., 3., 4.],
                  [4., 5., 6., 7.]])

print("A + B =\n", A + B)
print("A * B =\n", A * B)
print("A / B =\n", A / B)
print("Trung binh theo cot =", A.mean(dim=0))
print("Do lech chuan theo cot =", A.std(dim=0))

# 3. Autograd: y = 2*x^2 + 5*x + 3 tai x = 2
x_autograd = torch.tensor(2., requires_grad=True)
y_autograd = 2 * x_autograd**2 + 5 * x_autograd + 3
y_autograd.backward()
manual_derivative = 4 * 2 + 5
print("dy/dx bang autograd =", x_autograd.grad.item())
print("dy/dx thu cong =", manual_derivative)

# 4. Huan luyen y = 2*x^2 - 3*x + 5
x_train = torch.linspace(-5, 5, 101)
y_train = 2 * x_train**2 - 3 * x_train + 5

coefficients = torch.randn(3, requires_grad=True)
optimizer = torch.optim.Adam([coefficients], lr=0.05)

for epoch in range(2000):
    prediction = (coefficients[0] * x_train**2
                  + coefficients[1] * x_train
                  + coefficients[2])
    loss = torch.mean((prediction - y_train)**2)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

print("He so tim duoc [a, b, c] =", coefficients.detach())
print("Gia tri ky vong gan [2, -3, 5]")
print("Loss cuoi =", loss.item())

X =
 tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24])
X reshape (4, 6) =
 tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]])
X reshape (2, 12) =
 tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])
X reshape (2, 3, 4) =
 tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])
A + B =
 tensor([[ 3.,  6.,  9., 12.],
        [ 6.,  8., 10., 12.],
        [13., 15., 17., 19.]])
A * B =
 tensor([[ 2.,  8., 18., 32.],
        [ 5., 12., 21., 32.],
        [36., 50., 66., 84.]])
A / B =
 tensor([[0.5000, 0.5000, 0.5000, 0.5000],
        [5.0000, 3.0000, 2.3333, 2.0000],
        [2.2500, 2.0000, 1.8333, 1.7143]])
Trung binh theo cot = tensor([5., 6., 7., 8.])
Do lech chuan t